#
# Build go project
#
FROM golang:1.21-alpine as go-builder

WORKDIR /app

COPY . .

RUN apk add -u -t build-tools curl git
RUN go build -o server *.go

#
# Runtime container
#
FROM scratch

WORKDIR /app

COPY --from=go-builder /app/server .

EXPOSE 8080

ENTRYPOINT ["/app/server"]
